In [1]:
import numpy as np

In [2]:
np.__version__

'2.3.4'

## Nd Arrays

#### 1D

In [11]:
arr = np.array([1,2,3,4,5,6])
arr

array([1, 2, 3, 4, 5, 6])

In [12]:
type(arr)

numpy.ndarray

In [13]:
arr.shape

(6,)

In [14]:
arr.dtype

dtype('int64')

In [15]:
arr.ndim

1

In [16]:
arr.size

6

#### 2D

In [18]:
arr2 = np.array([[1,2,3],[4,5,6]])

In [23]:
arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [19]:
arr2.shape

(2, 3)

In [20]:
arr2.ndim

2

In [21]:
arr2.dtype

dtype('int64')

In [22]:
arr2.size

6

In [24]:
arr3 = np.array([[[1,2,3],[4,5,6]] , [[1,2,3],[4,5,6]] , [[1,2,3],[4,5,6]]])
arr3

array([[[1, 2, 3],
        [4, 5, 6]],

       [[1, 2, 3],
        [4, 5, 6]],

       [[1, 2, 3],
        [4, 5, 6]]])

In [25]:
arr3.ndim

3

In [26]:
arr3.shape

(3, 2, 3)

In [28]:
arr3.dtype

dtype('int64')

In [29]:
arr3.size

18

In [30]:
arr = np.random.rand(3,2,3)
arr

array([[[0.32911433, 0.68219098, 0.77669266],
        [0.30021574, 0.49773785, 0.19830528]],

       [[0.4727407 , 0.17616995, 0.29565144],
        [0.88827815, 0.73317265, 0.66395743]],

       [[0.95977341, 0.13732713, 0.1468238 ],
        [0.08054156, 0.62481311, 0.94012625]]])

In [31]:
zero = np.zeros([3,2,3])
zero

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [32]:
arr1 = np.full([3,2,3] , 8)
arr1

array([[[8, 8, 8],
        [8, 8, 8]],

       [[8, 8, 8],
        [8, 8, 8]],

       [[8, 8, 8],
        [8, 8, 8]]])

In [34]:
arr4 = np.array([[[1,2,3],[4,5,6]] , [[1,7,3],[6,5,6]] , [[9,2,3],[0,5,6]]])
arr4

array([[[1, 2, 3],
        [4, 5, 6]],

       [[1, 7, 3],
        [6, 5, 6]],

       [[9, 2, 3],
        [0, 5, 6]]])

In [37]:
arr4[0][0][0]

np.int64(1)

In [38]:
arr4[0:2]

array([[[1, 2, 3],
        [4, 5, 6]],

       [[1, 7, 3],
        [6, 5, 6]]])

In [39]:
arr4[-1]

array([[9, 2, 3],
       [0, 5, 6]])

In [40]:
arr4[1][0][1]

np.int64(7)

In [41]:
a1 = np.random.rand(2 , 3 , 2)
a2 = np.random.rand(2 , 3 , 2)

In [42]:
a1

array([[[0.5702012 , 0.86549406],
        [0.43747164, 0.59890769],
        [0.89452495, 0.54270513]],

       [[0.97356054, 0.96558824],
        [0.86528019, 0.07665962],
        [0.73769788, 0.3885113 ]]])

In [43]:
a2

array([[[0.51665187, 0.82674946],
        [0.6126665 , 0.77505375],
        [0.39710562, 0.21639801]],

       [[0.76002691, 0.03733213],
        [0.7126575 , 0.58804328],
        [0.13224719, 0.47417524]]])

In [44]:
#Basic Math Operations

In [45]:
np.add(a1 , a2)

array([[[1.08685307, 1.69224352],
        [1.05013814, 1.37396144],
        [1.29163057, 0.75910314]],

       [[1.73358745, 1.00292037],
        [1.57793769, 0.66470289],
        [0.86994507, 0.86268654]]])

In [46]:
np.subtract(a1 , a2)

array([[[ 0.05354933,  0.0387446 ],
        [-0.17519486, -0.17614605],
        [ 0.49741933,  0.32630712]],

       [[ 0.21353363,  0.9282561 ],
        [ 0.15262268, -0.51138366],
        [ 0.60545069, -0.08566394]]])

In [47]:
np.divide(a1 , a2)

array([[[ 1.10364683,  1.04686378],
        [ 0.71404531,  0.77273053],
        [ 2.25261215,  2.50790258]],

       [[ 1.28095535, 25.8648015 ],
        [ 1.21415993,  0.1303639 ],
        [ 5.5781742 ,  0.81934118]]])

In [48]:
np.multiply(a1 , a2)

array([[[0.29459552, 0.71554675],
        [0.26802422, 0.46418565],
        [0.35522089, 0.11744031]],

       [[0.73993221, 0.03604747],
        [0.61664842, 0.04507917],
        [0.09755847, 0.18422244]]])

In [51]:
# Stastical Operations

In [49]:
sqrt = np.sqrt(25)
abs1 = np.abs(-2)
power = np.power(2,8)
log = np.log(25)
mins = np.min(a1)
maxs = np.max(a2)

In [50]:
print(sqrt)

5.0


In [53]:
abs1

np.int64(2)

In [54]:
power

np.int64(256)

In [55]:
log

np.float64(3.2188758248682006)

In [56]:
mins

np.float64(0.07665961698252088)

In [57]:
maxs

np.float64(0.8267494602815925)

In [59]:
arr4

array([[[1, 2, 3],
        [4, 5, 6]],

       [[1, 7, 3],
        [6, 5, 6]],

       [[9, 2, 3],
        [0, 5, 6]]])

In [60]:
arr4.sort()

In [61]:
arr4

array([[[1, 2, 3],
        [4, 5, 6]],

       [[1, 3, 7],
        [5, 6, 6]],

       [[2, 3, 9],
        [0, 5, 6]]])

In [62]:
arr4.shape

(3, 2, 3)

In [63]:
arr4.size

18

In [64]:
arr4.reshape((2 , 3 , 3))

array([[[1, 2, 3],
        [4, 5, 6],
        [1, 3, 7]],

       [[5, 6, 6],
        [2, 3, 9],
        [0, 5, 6]]])

In [69]:
zero

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [72]:
new_array = np.ones((3 ,2 ,3))
new_array

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

In [74]:
append = np.append(zero , new_array , axis = 0)
append

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

In [75]:
append = np.append(zero , new_array , axis = 1)
append

array([[[0., 0., 0.],
        [0., 0., 0.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [1., 1., 1.],
        [1., 1., 1.]]])

In [77]:
append = np.append(zero , new_array , axis = 2)
append

array([[[0., 0., 0., 1., 1., 1.],
        [0., 0., 0., 1., 1., 1.]],

       [[0., 0., 0., 1., 1., 1.],
        [0., 0., 0., 1., 1., 1.]],

       [[0., 0., 0., 1., 1., 1.],
        [0., 0., 0., 1., 1., 1.]]])

In [79]:
inserted_array = np.insert(zero , 2 , new_array , axis = 0)
inserted_array

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [80]:
array = np.random.rand(3 , 2 , 3)

In [86]:
array

array([[[0.56225819, 0.41739275, 0.81606958],
        [0.74355094, 0.27034344, 0.84953924]],

       [[0.60909406, 0.70842636, 0.47638409],
        [0.29853294, 0.87301457, 0.61784252]],

       [[0.77735703, 0.45921981, 0.43793384],
        [0.71157168, 0.74472435, 0.51393836]]])

In [87]:
arr5 = np.delete(array , 0 , axis = 2)

In [88]:
arr5

array([[[0.41739275, 0.81606958],
        [0.27034344, 0.84953924]],

       [[0.70842636, 0.47638409],
        [0.87301457, 0.61784252]],

       [[0.45921981, 0.43793384],
        [0.74472435, 0.51393836]]])

In [89]:
np.save('new_array' , arr5)

In [91]:
np.load('new_array.npy')

array([[[0.41739275, 0.81606958],
        [0.27034344, 0.84953924]],

       [[0.70842636, 0.47638409],
        [0.87301457, 0.61784252]],

       [[0.45921981, 0.43793384],
        [0.74472435, 0.51393836]]])